### ISSUE TITLE
Doubt with the verification/check using the MySQL database

### ISSUE THREAD

**Issue by crashzk** [azalty/sm-no-dupe-account#13]
I currently have 5 servers, 2 competitive and 3 casual.

On competitive servers I have a requirement using your plugin that has to have 150 hours played on CSGO to enter the servers, and 45 hours played on CSGO to enter the casual servers.

I am currently using the plugin with the MySQL database, my question would be.

Players who enter casual servers, having at least 60 hours of play on CSGO for example, would be able to enter competitive servers that need to have 150 hours of play on CSGO?

I ask because I use the same database for all servers, only the configuration that changes. Or the plugin, even if it is in MySQL, uses the configuration of each server to check the requirements.

In this case, I want him to enter only if he passes all checks and has the requirements to connect. Then I was left with doubts at that time, **`nda_playtime"150"`**.

I know I could use SQLite to solve this, but I would like to use MySQL because I am thinking of setting up a web interface to show the players who have access to the servers and those who do not have access to connect yet.

**Comment by azalty** [comment]
The database stores player values, including playtime, and doesn't store wether or not the player should be accepted. The server will only retrieve players' playtime from the database and do all the verifications locally. So no, a player with 60h of playtime will **not** be able to connect to the competitive server.

~~Please be aware that there is currently a bug about playtime not saving into the database. It has been fixed BUT a new version wasn't released yet. (#11)~~

~~To have this fix, please download directly the main branch (only scripting and plugins changed)~~

**edit: 1.4.1 was released, and it was about steam level&age, not csgo playtime!**

**Comment by azalty** [comment]
btw, if you want players to have at least 45h or 150h, you probably don't need to use other checks, since they'll probably all be legit players

casual: `nda_playtime "-2700"` (time in minutes, so 60mins * 45h)
competitive: `nda_playtime "-9000"` (time in minutes, so 60mins * 150h)

The "-" prefix will specify how many minutes a player needs, and set it as a requirement instead of a check (at least for that cvar) [(see what's a check here)](https://github.com/azalty/sm-no-dupe-account/wiki/FAQ#whats-a-check). While having only 1 check will make the plugin behave like it's a requirement, it will have a less precise kick message, saying that the account is suspicious.

[You can also see here advanced infos about the DB system, in case that helps](https://github.com/azalty/sm-no-dupe-account/wiki/How-the-database-works)

**Comment by crashzk** [comment]
Thanks, I'll check everything out.

Anything I return contact.
