### ISSUE TITLE
Create NDA log file

### ISSUE THREAD

**Issue by crashzk** [azalty/sm-no-dupe-account#25]
We currently have the following logging option for NDA:
```
// 0 = don't log
// 1 = log check approvals & refusals to server's console
// 2 = log check refusals to server's console
// -
// Default: "1"
nda_log "1"
```
Even having everything saved in **`console.log`** would be a good thing, I believe he creates a file to have his own logs.

The suggestion is there, who knows in the future.

**Comment by azalty** [comment]
Well, it is currently sent to the server's console.
If you enabled logging, it should appear as well in console.log, since this file contains everything the console outputs.

How to do it? Add `-condebug` in your srcds command line.

Other commands could work too, I don't really know, I just use -condebug on all my servers
https://forums.alliedmods.net/showthread.php?t=178551 - https://forums.alliedmods.net/showthread.php?t=170786

**Comment by crashzk** [comment]
I see, I think I'll keep it on console.log, thank you.
