### ISSUE TITLE
Log even more things! (nda_log 3)

### ISSUE THREAD

**Issue by azalty** [azalty/sm-no-dupe-account#26]
Add `nda_log 3` : log approvals, refusals and developer infos (useful for debugging, or manual profiling of players)

Developer infos include:
- Client's database status (1, 2 or 3) on OnClientPostAdminCheck(), with [their meaning](https://github.com/azalty/sm-no-dupe-account/wiki/How-the-database-works#advanced-how-it-works).
- Client's new database values: `Updated %L into the database: csgo_level=X, csgo_coin=X, ...`

This allows myself to better see potential problems with those values, and you to better report those kind of issues.

It also allows you to profile manually each player: ex: get csgo_playtime, steam_age if you're not sure if the player is using a duplicate account, and the player changed their profile to be private. This will also allow you to see if the player previously connected to the server (status = 3 if they didn't).

**Q: Why do I want to add this?**
A: I already added this in my developer version. It might be time for me to add it to the official versions :)
I really think it helps, and I've been using these logs for some time now, and they're really useful!

**Comment by azalty** [comment]
This has been done in 1.5.0 Beta 2 ([commit](https://github.com/azalty/sm-no-dupe-account/commit/4276298254087d82480182f134f643a7d16d3fdb))

**Comment by crashzk** [comment]
@azalty just a feedack of the **`1.5.0 Beta 2`** version.

I've been using this version for 3 days, so far the plugin itself works from what I could see, but I noticed some BUGS in the checks.

Not in the verification, so I believe, but at the time, a player himself played an almost full competition today, 18 rounds and only later got kicked because he had his private profile.

http://steamcommunity.com/profiles/76561198809531208

Then he simply retry, and checking the database I saw that he still doesn't have his steam registered, and even so after the retry he managed to stay connected.

Also attached is the database you want to check.

[players.zip](https://github.com/azalty/sm-no-dupe-account/files/7360530/players.zip)

I noticed that this doesn't always happen, rare cases and with some players only.

**Comment by azalty** [comment]
@crashzk 
Did you enable logging? (nda_log 1, 2 or 3)
If so, could you send me the logs in your console?
Please hide any IP or sensitive info

**Comment by azalty** [comment]
@crashzk I couldn't find that player's steamid in the database
Are you sure this bug only started to occur since 1.5.0 Beta 2?

Could you show the kick message and NDA's log messages?

**Comment by crashzk** [comment]
Yes, I have the cvar configured:
```
// 0 = don't log
// 1 = log check approvals & refusals to server's console
// 2 = log check refusals to server's console
// 3 = log approvals, refusals and developer infos (useful for debugging or manual profiling of players)
// -
// Default: "1"
nda_log "1"
```
But I don't have the **`-condebug`** command enabled, I'll be checking with my host if it's possible to activate it for me and I'll come back with more information as soon as possible.

About the player, yes, as I mentioned, it doesn't have its SteamID registered in the database.

About the kick message, I don't remember exactly what it was, but it was one of these:
```
	"Kicked_PrivatePlaytime"
	{
		"en"	"You need to display your profile and your playtime publicly. To do this, go to the privacy options of your Steam Profile"
	}
	
	"Kicked_PrivateProfile"
	{
		"en"	"You need to display your profile publicly. To do this, go to the privacy options of your Steam Profile"
	}
```
I'll see if I can get more data and return here.

**Comment by azalty** [comment]
@crashzk If this still happens, please create a new issue so we can figure out the problem

**Comment by crashzk** [comment]
Perfect, anything open a new issues, thanks

**Comment by azalty** [comment]
Added in the 1.5.0 stable release.
