### ISSUE TITLE
Implement database system

### ISSUE THREAD

**Issue by crashzk** [azalty/sm-no-dupe-account#5]
Implement a database system, thus storing the playes that have already passed the checks.

An example for using this function would be for private profiles and hours of play played, once the verification is done, the player can leave his profile private again if he has all the requirements.

**Comment by azalty** [comment]
Currently working on it.

**Comment by azalty** [comment]
This is taking longer than expected. Code probably needs some rewriting, I have to figure out a way to do what I want properly.

I hope I can finish this in the following hours

**Comment by azalty** [comment]
The database system in itself is done and seems working (on the big lines at least)

I still have to do some testing, small fixes and adjustments. ETA could be tomorrow, but i'm really unsure because I could be lazy hehe

You should get this update in a few days, thank you for your interest in my plugin :)

**Comment by crashzk** [comment]
Thank you, I thank you for this magnificent plugin.

I'll be waiting without any problems.

**Comment by azalty** [comment]
Done! It's available in 1.4.0

If you find any bug, please report them :)

**Comment by crashzk** [comment]
I'll be testing, anything I'll contact.
